import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useMutation } from "@tanstack/react-query";
import { useEffect, useId, useState, type FormEvent } from "react";
import heroGlobe from "@/assets/hero-globe.jpg";
import { generateContract } from "@/lib/contract.functions";
import { signInWithPi, getCachedPiUser, payAppWithPi, getCachedPiAccessToken } from "@/lib/pi-auth";
import { ChatBot } from "@/components/ChatBot";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "PiTrade — AI Borderless Trade Contracts on Pi" },
      { name: "description", content: "Draft borderless import & export smart contracts for any commodity, settled in Pi (π), generated by AI in seconds." },
      { property: "og:title", content: "PiTrade — AI Borderless Trade Contracts on Pi" },
      { property: "og:description", content: "Generate Pi-settled smart contracts for global trade in any commodity." },
    ],
    links: [
      { rel: "canonical", href: "https://pi-trade-flow.lovable.app/" },
    ],
    scripts: [
      {
        type: "application/ld+json",
        children: JSON.stringify({
          "@context": "https://schema.org",
          "@graph": [
            {
              "@type": "WebSite",
              name: "PiTrade",
              url: "https://pi-trade-flow.lovable.app/",
              description: "AI-drafted borderless import & export smart contracts settled in Pi (π).",
            },
            {
              "@type": "Service",
              name: "PiTrade Smart Contract Drafting",
              serviceType: "International trade contract drafting",
              description: "Generate Pi-settled smart contracts for global import and export of any commodity, with Incoterms 2020 coverage and on-chain escrow on the Pi Network.",
              areaServed: "Worldwide",
              provider: {
                "@type": "Organization",
                name: "PiTrade",
                url: "https://pi-trade-flow.lovable.app/",
              },
            },
          ],
        }),
      },
    ],
  }),
  component: Index,
});

const DEFAULTS = {
  commodity: "Arabica green coffee beans, Grade 1",
  quantity: "20 metric tons (1 x 20ft FCL)",
  exporter: "Highland Coffee Cooperative",
  exporterCountry: "Ethiopia",
  importer: "Nordic Roasters AB",
  importerCountry: "Sweden",
  incoterm: "CIF Gothenburg",
  priceInPi: "π 48,500 total",
  deliveryWindow: "Shipment within 45 days of contract execution",
  notes: "Buyer requires SCA cupping score ≥ 85. Phytosanitary certificate required.",
};

function Index() {
  const generate = useServerFn(generateContract);
  const [form, setForm] = useState(DEFAULTS);
  const [piUser, setPiUser] = useState<{ uid: string; username: string } | null>(
    null,
  );
  const [piError, setPiError] = useState<string | null>(null);
  const [piPending, setPiPending] = useState(false);
  const [payAmount, setPayAmount] = useState("1");
  const [payMemo, setPayMemo] = useState("PiTrade contract drafting credit");
  const [payPending, setPayPending] = useState(false);
  const [payError, setPayError] = useState<string | null>(null);
  const [payReceipt, setPayReceipt] = useState<{
    paymentId: string;
    txid: string;
    amount: number;
  } | null>(null);

  const handlePiSignIn = async () => {
    setPiError(null);
    setPiPending(true);
    try {
      const user = await signInWithPi();
      setPiUser(user);
    } catch (e) {
      setPiError(e instanceof Error ? e.message : "Pi sign-in failed");
    } finally {
      setPiPending(false);
    }
  };

  const handlePay = async () => {
    setPayError(null);
    setPayReceipt(null);
    const amount = Number(payAmount);
    if (!Number.isFinite(amount) || amount <= 0) {
      setPayError("Enter an amount greater than 0 π");
      return;
    }
    if (!piUser) {
      try {
        await handlePiSignIn();
      } catch {
        return;
      }
    }
    setPayPending(true);
    try {
      const result = await payAppWithPi({
        amount,
        memo: payMemo || "PiTrade payment",
        metadata: {
          product: "pitrade.contract_credit",
          username: getCachedPiUser()?.username ?? null,
        },
      });
      setPayReceipt({ ...result, amount });
    } catch (e) {
      setPayError(e instanceof Error ? e.message : "Payment failed");
    } finally {
      setPayPending(false);
    }
  };

  useEffect(() => {
    const cached = getCachedPiUser();
    if (cached) {
      setPiUser(cached);
      return;
    }
    void handlePiSignIn();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const mutation = useMutation({
    mutationFn: async (data: typeof DEFAULTS) => {
      let accessToken = getCachedPiAccessToken();
      if (!accessToken) {
        await handlePiSignIn();
        accessToken = getCachedPiAccessToken();
      }
      if (!accessToken) throw new Error("Please sign in with Pi to generate contracts.");
      return generate({ data: { ...data, accessToken } });
    },
  });

  const onSubmit = (e: FormEvent) => {
    e.preventDefault();
    mutation.mutate(form);
    requestAnimationFrame(() => {
      document.getElementById("contract-output")?.scrollIntoView({ behavior: "smooth" });
    });
  };

  const update = (k: keyof typeof DEFAULTS) => (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) =>
    setForm((f) => ({ ...f, [k]: e.target.value }));

  return (
    <main className="min-h-screen bg-background text-foreground font-sans">
      {/* NAV */}
      <header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6">
        <div className="flex items-center gap-2">
          <span className="grid h-9 w-9 place-items-center rounded-sm bg-primary text-primary-foreground font-display text-xl">π</span>
          <span className="font-display text-2xl tracking-tight">PiTrade</span>
        </div>
        <nav className="hidden gap-8 text-sm text-muted-foreground md:flex">
          <a href="#how" className="hover:text-foreground">How it works</a>
          <a href="#features" className="hover:text-foreground">Capabilities</a>
          <a href="#generator" className="hover:text-foreground">Draft contract</a>
        </nav>
        <div className="flex items-center gap-3">
          {piUser ? (
            <span className="rounded-sm border border-border px-3 py-2 text-xs text-muted-foreground">
              π @{piUser.username}
            </span>
          ) : (
            <button
              type="button"
              onClick={handlePiSignIn}
              disabled={piPending}
              className="rounded-sm border border-border px-4 py-2 text-sm text-foreground hover:bg-secondary disabled:opacity-50"
            >
              {piPending ? "Signing in…" : "Sign in with Pi"}
            </button>
          )}
          <a href="#generator" className="rounded-sm bg-primary px-4 py-2 text-sm text-primary-foreground hover:opacity-90">
            Launch
          </a>
        </div>
      </header>
      {piError && (
        <div className="mx-auto max-w-7xl px-6">
          <p className="rounded-sm border border-destructive bg-destructive/10 px-3 py-2 text-xs text-destructive-foreground">
            Pi sign-in: {piError} — open this app inside the Pi Browser to authenticate.
          </p>
        </div>
      )}

      {/* HERO */}
      <section
        className="relative overflow-hidden border-b border-border"
        style={{ background: "var(--gradient-hero)" }}
      >
        <div className="mx-auto grid max-w-7xl items-center gap-12 px-6 py-20 lg:grid-cols-[1.1fr_1fr] lg:py-28">
          <div>
            <p className="mb-6 inline-block rounded-sm border border-border bg-card/40 px-3 py-1 text-xs uppercase tracking-[0.18em] text-muted-foreground">
              Borderless trade · Pi Ecosystem · AI-drafted
            </p>
            <h1 className="font-display text-5xl leading-[1.05] tracking-tight md:text-7xl">
              Move goods across borders. <span className="italic text-primary">Settle in Pi.</span>
            </h1>
            <p className="mt-6 max-w-xl text-lg text-muted-foreground">
              PiTrade drafts legally-credible import &amp; export smart contracts for any commodity on Earth — denominated in π, escrowed on the Pi Network, and generated by AI in seconds.
            </p>
            <div className="mt-8 flex flex-wrap gap-3">
              <a href="#generator" className="rounded-sm bg-primary px-6 py-3 text-sm font-medium text-primary-foreground shadow-[var(--shadow-elegant)] hover:opacity-90">
                Draft a contract
              </a>
              <a href="#how" className="rounded-sm border border-border px-6 py-3 text-sm text-foreground hover:bg-secondary">
                How it works
              </a>
            </div>
            <dl className="mt-12 grid max-w-lg grid-cols-3 gap-6 border-t border-border pt-8 text-sm">
              {[
                ["180+", "Jurisdictions"],
                ["Incoterms 2020", "Fully covered"],
                ["π Mainnet", "On-chain escrow"],
              ].map(([k, v]) => (
                <div key={v}>
                  <dt className="font-display text-2xl text-foreground">{k}</dt>
                  <dd className="text-muted-foreground">{v}</dd>
                </div>
              ))}
            </dl>
          </div>
          <div className="relative">
            <img
              src={heroGlobe}
              alt="Global trade network settling in Pi"
              width={1600}
              height={1200}
              fetchPriority="high"
              decoding="async"
              className="rounded-sm border border-border shadow-[var(--shadow-elegant)]"
            />
          </div>
        </div>
      </section>

      {/* CAPABILITIES GRID */}
      <section id="features" className="border-b border-border">
        <div className="mx-auto max-w-7xl px-6 py-20">
          <div className="mb-12 flex items-end justify-between gap-6">
            <h2 className="font-display text-4xl md:text-5xl">Capabilities</h2>
            <p className="max-w-md text-sm text-muted-foreground">A complete drafting stack for cross-border trade, built around the Pi smart-contract layer.</p>
          </div>
          <div className="grid gap-px overflow-hidden rounded-sm border border-border bg-border md:grid-cols-3">
            {[
              { t: "All commodities", d: "From green coffee and copper concentrate to rare earths, textiles, electronics, agri and energy.", n: "01" },
              { t: "Pi-denominated escrow", d: "Funds locked in a Pi smart contract; milestone releases on Bill of Lading and inspection oracles.", n: "02" },
              { t: "Incoterms 2020", d: "FOB, CIF, DAP, DDP and the rest, applied with the right risk/title transfer clauses.", n: "03" },
              { t: "Customs & compliance", d: "AI-assisted HS code classification, sanctions screening, dual-use checks at draft time.", n: "04" },
              { t: "Pi DAO arbitration", d: "Dispute resolution via Pi DAO with ICC fallback and a neutral governing law.", n: "05" },
              { t: "Borderless parties", d: "Any exporter, any importer, any pair of countries. Counterparties verified via Pi KYC.", n: "06" },
            ].map((f) => (
              <article key={f.t} className="bg-background p-8 transition-colors hover:bg-card">
                <p className="font-display text-sm text-primary">{f.n}</p>
                <h3 className="mt-4 font-display text-2xl">{f.t}</h3>
                <p className="mt-3 text-sm text-muted-foreground">{f.d}</p>
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* HOW */}
      <section id="how" className="border-b border-border bg-card/30">
        <div className="mx-auto max-w-7xl px-6 py-20">
          <h2 className="mb-12 font-display text-4xl md:text-5xl">How it works</h2>
          <ol className="grid gap-8 md:grid-cols-3">
            {[
              ["Describe the deal", "Enter commodity, parties, quantity, Incoterm, delivery window and Pi price."],
              ["AI drafts the contract", "Gemini-powered drafting engine produces a signature-ready, Pi-settled agreement."],
              ["Execute on Pi", "Both parties sign; funds escrow on Pi mainnet and release on shipment milestones."],
            ].map(([t, d], i) => (
              <li key={t} className="rounded-sm border border-border bg-background p-8">
                <p className="font-display text-4xl text-primary">{String(i + 1).padStart(2, "0")}</p>
                <h3 className="mt-3 font-display text-2xl">{t}</h3>
                <p className="mt-2 text-sm text-muted-foreground">{d}</p>
              </li>
            ))}
          </ol>
        </div>
      </section>

      {/* GENERATOR */}
      <section id="generator" className="border-b border-border">
        <div className="mx-auto max-w-7xl px-6 py-20">
          <div className="mb-10 flex flex-wrap items-end justify-between gap-6">
            <div>
              <p className="text-xs uppercase tracking-[0.18em] text-primary">Draft contract</p>
              <h2 className="mt-2 font-display text-4xl md:text-5xl">A new agreement, in any commodity</h2>
            </div>
            <p className="max-w-sm text-sm text-muted-foreground">
              Fill in the deal terms. The AI will produce a complete, Pi-settled import/export contract you can review, edit and sign.
            </p>
          </div>

          <form onSubmit={onSubmit} className="grid gap-6 rounded-sm border border-border bg-card p-8 md:grid-cols-2">
            <Field label="Commodity / Goods" value={form.commodity} onChange={update("commodity")} />
            <Field label="Quantity" value={form.quantity} onChange={update("quantity")} />
            <Field label="Exporter" value={form.exporter} onChange={update("exporter")} />
            <Field label="Exporter country" value={form.exporterCountry} onChange={update("exporterCountry")} />
            <Field label="Importer" value={form.importer} onChange={update("importer")} />
            <Field label="Importer country" value={form.importerCountry} onChange={update("importerCountry")} />
            <Field label="Incoterm 2020" value={form.incoterm} onChange={update("incoterm")} placeholder="e.g. CIF Gothenburg" />
            <Field label="Price in Pi (π)" value={form.priceInPi} onChange={update("priceInPi")} />
            <Field label="Delivery window" value={form.deliveryWindow} onChange={update("deliveryWindow")} className="md:col-span-2" />
            <NotesField value={form.notes} onChange={update("notes")} />
            <div className="md:col-span-2 flex flex-wrap items-center justify-between gap-4 border-t border-border pt-6">
              <p className="text-xs text-muted-foreground">By generating you accept this is a drafting tool. Have counsel review before signing.</p>
              <button
                type="submit"
                disabled={mutation.isPending}
                className="rounded-sm bg-primary px-6 py-3 text-sm font-medium text-primary-foreground shadow-[var(--shadow-elegant)] hover:opacity-90 disabled:opacity-50"
              >
                {mutation.isPending ? "Drafting contract…" : "Generate Pi smart contract"}
              </button>
            </div>
          </form>

          <div id="contract-output" className="mt-10">
            {mutation.isError && (
              <div className="rounded-sm border border-destructive bg-destructive/10 p-6 text-sm text-destructive-foreground">
                {(mutation.error as Error).message}
              </div>
            )}
            {mutation.data?.contract && (
              <article className="rounded-sm border border-border bg-card p-8 md:p-12">
                <header className="mb-6 flex items-center justify-between border-b border-border pb-4">
                  <p className="text-xs uppercase tracking-[0.18em] text-primary">Generated draft</p>
                  <button
                    type="button"
                    onClick={() => navigator.clipboard.writeText(mutation.data!.contract)}
                    className="text-xs text-muted-foreground hover:text-foreground"
                  >
                    Copy markdown
                  </button>
                </header>
                <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed text-foreground">{mutation.data.contract}</pre>
              </article>
            )}
          </div>
        </div>
      </section>

      {/* PAY WITH PI */}
      <section id="pay" className="border-b border-border bg-card/30">
        <div className="mx-auto max-w-3xl px-6 py-20">
          <p className="text-xs uppercase tracking-[0.18em] text-primary">In-app payment</p>
          <h2 className="mt-2 font-display text-4xl md:text-5xl">Pay PiTrade in π</h2>
          <p className="mt-3 max-w-xl text-sm text-muted-foreground">
            Send Pi directly to PiTrade from the Pi Browser. The payment is approved and completed
            server-side against the Pi Platform API.
          </p>

          <div className="mt-8 grid gap-4 rounded-sm border border-border bg-background p-6 md:grid-cols-[1fr_2fr_auto] md:items-end">
            <PayAmountField value={payAmount} onChange={(e) => setPayAmount(e.target.value)} />
            <PayMemoField value={payMemo} onChange={(e) => setPayMemo(e.target.value)} />
            <button
              type="button"
              onClick={handlePay}
              disabled={payPending}
              className="h-10 rounded-sm bg-primary px-6 text-sm font-medium text-primary-foreground shadow-[var(--shadow-elegant)] hover:opacity-90 disabled:opacity-50"
            >
              {payPending ? "Processing…" : `Pay π ${payAmount || "0"}`}
            </button>
          </div>

          {payError && (
            <div className="mt-4 rounded-sm border border-destructive bg-destructive/10 p-4 text-sm text-destructive-foreground">
              {payError}
            </div>
          )}
          {payReceipt && (
            <div className="mt-4 rounded-sm border border-border bg-background p-4 text-sm">
              <p className="font-display text-lg text-primary">Payment complete · π {payReceipt.amount}</p>
              <p className="mt-1 break-all text-xs text-muted-foreground">paymentId: {payReceipt.paymentId}</p>
              <p className="break-all text-xs text-muted-foreground">txid: {payReceipt.txid}</p>
            </div>
          )}
          <p className="mt-4 text-xs text-muted-foreground">
            Pi payments only run inside the Pi Browser with a signed-in Pi account.
          </p>
        </div>
      </section>

      <footer className="mx-auto max-w-7xl px-6 py-10 text-xs text-muted-foreground">
        <div className="flex flex-wrap items-center justify-between gap-4 border-t border-border pt-8">
          <p>© {new Date().getFullYear()} PiTrade — borderless commerce on the Pi Network.</p>
          <p className="font-display italic">π · Trade without borders</p>
        </div>
      </footer>

      <ChatBot />
    </main>
  );
}

function Field({
  label,
  className = "",
  ...props
}: React.InputHTMLAttributes<HTMLInputElement> & { label: string; className?: string }) {
  const id = useId();
  return (
    <div className={className}>
      <label htmlFor={id} className="mb-2 block text-xs uppercase tracking-[0.16em] text-muted-foreground">{label}</label>
      <input
        id={id}
        {...props}
        className="w-full rounded-sm border border-border bg-input/40 px-3 py-2 text-sm text-foreground outline-none placeholder:text-muted-foreground/60 focus:border-primary"
      />
    </div>
  );
}

function NotesField({
  value,
  onChange,
}: {
  value: string;
  onChange: (e: React.ChangeEvent<HTMLTextAreaElement>) => void;
}) {
  const id = useId();
  return (
    <div className="md:col-span-2">
      <label htmlFor={id} className="mb-2 block text-xs uppercase tracking-[0.16em] text-muted-foreground">
        Additional notes
      </label>
      <textarea
        id={id}
        value={value}
        onChange={onChange}
        rows={3}
        className="w-full rounded-sm border border-border bg-input/40 px-3 py-2 text-sm text-foreground outline-none placeholder:text-muted-foreground/60 focus:border-primary"
      />
    </div>
  );
}

function PayAmountField({
  value,
  onChange,
}: {
  value: string;
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
}) {
  const id = useId();
  return (
    <div>
      <label htmlFor={id} className="mb-2 block text-xs uppercase tracking-[0.16em] text-muted-foreground">
        Amount (π)
      </label>
      <input
        id={id}
        type="number"
        min="0"
        step="0.01"
        value={value}
        onChange={onChange}
        className="w-full rounded-sm border border-border bg-input/40 px-3 py-2 text-sm text-foreground outline-none focus:border-primary"
      />
    </div>
  );
}

function PayMemoField({
  value,
  onChange,
}: {
  value: string;
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
}) {
  const id = useId();
  return (
    <div>
      <label htmlFor={id} className="mb-2 block text-xs uppercase tracking-[0.16em] text-muted-foreground">
        Memo
      </label>
      <input
        id={id}
        type="text"
        value={value}
        onChange={onChange}
        maxLength={120}
        className="w-full rounded-sm border border-border bg-input/40 px-3 py-2 text-sm text-foreground outline-none focus:border-primary"
      />
    </div>
  );
}
